apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app-container
        image: messaging-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
