# docker-compose.yml

version: '3.8' # Specifies the version of the Docker Compose file format

services:
  # 1. The Database Service (MySQL)
  db:
    image: mysql:8.0 # Use the official MySQL image, version 8.0
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql # Persist database data using a named volume
    restart: always # Always restart the container if it stops
    environment:
      # Use variables from our .env file to configure MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  # 2. The Web Service (Your Django App)
  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: django_web
    command: sh -c /app/entrypoint.sh # Run our entrypoint script
    volumes:
      - .:/app # Map the current directory on the host to /app in the container for live code changes
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - .env # Load environment variables from the .env file
    restart: always
    depends_on:
      - db # This service depends on the 'db' service. It will start after 'db' starts.

# Top-level declaration for the named volume used by the db service
volumes:
  db_data: