apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    # Initially, all traffic goes to the blue deployment
    app: django-messaging-app
    version: blue
